### ISSUE TITLE
出现错误Parameter token or opts.auth is required，怎么弄？

### ISSUE THREAD

**Issue by shenzt68** [HoldOnBro/Actions-OpenWrt#1]
Run ncipollo/release-action@v1
Error: Error undefined: Parameter token or opts.auth is required
大侠怎么解决？

**Comment by HoldOnBro** [comment]
下面简介有使用方法。
简单来说就是你得在fork的项目里添加一个名为RELEASES_TOKEN的secret，这个token就是你github的Personal Access Token，怎么生成自行谷歌。

**Comment by Benjamin23333** [comment]
大佬，lienol寄放在xiaorouji那里的passwall仓库改名了

**Comment by Benjamin23333** [comment]
> 下面简介有使用方法。
> 简单来说就是你得在fork的项目里添加一个名为RELEASES_TOKEN的secret，这个token就是你github的Personal Access Token，怎么生成自行谷歌。

大佬，lienol寄放在xiaorouji那里的passwall仓库改名了

**Comment by HoldOnBro** [comment]
> > 下面简介有使用方法。
> > 简单来说就是你得在fork的项目里添加一个名为RELEASES_TOKEN的secret，这个token就是你github的Personal Access Token，怎么生成自行谷歌。
> 
> 大佬，lienol寄放在xiaorouji那里的passwall仓库改名了

感谢提醒，已更新
