### ISSUE TITLE
N1做单臂时上网延迟很大

### ISSUE THREAD

**Issue by aixufan** [HoldOnBro/Actions-OpenWrt#2]
不知道是否和DHCP里的DNS转发是否有关，我关闭相关进程并删掉2个转发的DNS直接无法上网。请大佬解疑

**Comment by HoldOnBro** [comment]
> 不知道是否和DHCP里的DNS转发是否有关，我关闭相关进程并删掉2个转发的DNS直接无法上网。请大佬解疑

没玩过单臂，不知道怎么解决。可以谷歌下详细配置和相关问题。
