### ISSUE TITLE
大佬我FOK了 你的仓库，这两个位置的数字的含义是设么呢

### ISSUE THREAD

**Issue by rq1025330** [HoldOnBro/Actions-OpenWrt#4]
![image](https://user-images.githubusercontent.com/52870887/124290774-6ade8280-db86-11eb-82d1-0f748012f4c1.png)
![image](https://user-images.githubusercontent.com/52870887/124290815-792c9e80-db86-11eb-96ef-bd4dc84e5b5f.png)

**Comment by rq1025330** [comment]
我 打包就报错应该就是这问题 ，不知道怎么改，

**Comment by rq1025330** [comment]
我改成latest 可以成功 有啥影响没得
![image](https://user-images.githubusercontent.com/52870887/124294330-1e954180-db8a-11eb-90f3-1d55c52da1fb.png)
还有这个文件我看代码里都没使用他  ，有什么特别作用？可以直接删除？

**Comment by HoldOnBro** [comment]
数字是我仓库的release id，github有api可以获取特定release的id。redo脚本是方便本地编译时更新上游插件用的，云编译用不到。

**Comment by rq1025330** [comment]
非常感谢大佬的耐心解答，因为不会编程语言所以才麻烦问了你。昨晚发现填写latest产生新的release就不能使用，我就自己摸索通过连接自己查看到了id了，还有就是着两个位置的id 。我现在两个位置的id是一样的,会有问题吗，还有就是getimg是不是可以不用，感觉重复了，如果都要，他们有优先顺序吗？会使用哪一个。以上提问有什么不对的，请大佬多包涵。再次感谢大佬！

**Comment by rq1025330** [comment]
非常感谢大佬的耐心解答，因为不会编程语言所以才麻烦问了你。昨晚发现填写latest产生新的release就不能使用，我就自己摸索通过连接自己查看到了id了，还有就是着两个位置的id 。我现在两个位置的id是一样的,会有问题吗，还有就是getimg是不是可以不用，感觉重复了，如果都要，他们有优先顺序吗？会使用哪一个。以上提问有什么不对的，请大佬多包涵。再次感谢大佬！

**Comment by rq1025330** [comment]
> 数字是我仓库的release id，github有api可以获取特定release的id。redo脚本是方便本地编译时更新上游插件用的，云编译用不到。

非常感谢大佬的耐心解答，因为不会编程语言所以才麻烦问了你。昨晚发现填写latest产生新的release就不能使用，我就自己摸索通过连接自己查看到了id了，还有就是着两个位置的id 。我现在两个位置的id是一样的,会有问题吗，还有就是getimg是不是可以不用，感觉重复了，如果都要，他们有优先顺序吗？会使用哪一个。以上提问有什么不对的，请大佬多包涵。再次感谢大佬！

**Comment by rq1025330** [comment]
还有就是 我这里编译经常超时 ，我看大佬你基本都编译成功呢？

**Comment by rq1025330** [comment]
非常感谢大佬的耐心解答，因为不会编程语言所以才麻烦问了你。昨晚发现填写latest产生新的release就不能使用，我就自己摸索通过连接自己查看到了id了，还有就是着两个位置的id 。我现在两个位置的id是一样的,会有问题吗，还有就是getimg是不是可以不用，感觉重复了，如果都要，他们有优先顺序吗？会使用哪一个。以上提问有什么不对的，请大佬多包涵。再次感谢大佬！

**Comment by rq1025330** [comment]
还有就是我编译经常都超时呀 ，我看大佬你基本都成功，这与什么原因？

**Comment by HoldOnBro** [comment]
getimgs是很久以前的脚本了，现在好像确实不用了，id以yml文件内的为准就行，get脚本其实是不执行的。  编译超时问题比较随缘，和机器性能以及同时间段其它人的占用多少有关，可以试试换着时间测试。

**Comment by rq1025330** [comment]
谢谢大佬

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/124378553-89f32680-dce4-11eb-9db6-6343cb04de80.png)
![image](https://user-images.githubusercontent.com/52870887/124378562-95465200-dce4-11eb-91eb-15ea9d9970ab.png)
![image](https://user-images.githubusercontent.com/52870887/124378670-38976700-dce5-11eb-8824-7e902b56e107.png)

大佬，用你的环境编译我的配置后，网络存储里面没有luci-app-syncthing这个应用。用P3TERX的仓库测试有这个应用，环境里没配置上图文件。我怀疑是上图配置文件的问题引起的。上图配置文件的作用是什么呢？，一定要配置？

**Comment by HoldOnBro** [comment]
和这些没关系，我仓库确实没添加这个，你要加得自己改diy2脚本，然后相应设备的配置文件xxx.config里也要选上这个插件。

**Comment by rq1025330** [comment]
我加了的在仓库里，但是编译出来不知道为啥就是没得.奇怪了，大佬要是你有空的话能帮我看下我的仓库有什么问题吗？

**Comment by rq1025330** [comment]
MY-开头就是我的

**Comment by rq1025330** [comment]
大佬我找到原因了 打包的安装包里面就没有 luci-app-syncthing_1.0-2_all.ipk，但是syncthing这个包在  ，出现这样的情况一般是什么原因呢第一次遇到！

**Comment by rq1025330** [comment]
最后发现问题竟是包名后面误输入字符造成文件名不对
