### ISSUE TITLE
N1 67+o 单臂无法打开docker的映射端口

### ISSUE THREAD

**Issue by aixufan** [HoldOnBro/Actions-OpenWrt#7]
比如QL映射出的5700端口，我是单臂用的，请教下是不是旁路由不会有这种问题。

**Comment by HoldOnBro** [comment]
配置问题可以加F大的tg群讨论哈，我现在只是日常维护下固件，机器也换成x86了，没法帮你测试 [加群链接](https://t.me/joinchat/InJrhXPcuJJiMDdl)

**Comment by aixufan** [comment]
> 比如QL映射出的5700端口，我是单臂用的，请教下是不是旁路由不会有这种问题。
